name: movia
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  cloud_firestore: ^6.1.2
  cloud_firestore_platform_interface: ^7.0.6
  cloud_firestore_web: ^5.1.2
  collection: 1.19.1
  csv: 6.0.0
  easy_debounce: ^2.0.3
  equatable: ^2.0.8
  firebase_auth: ^6.1.4
  firebase_auth_platform_interface: ^8.1.6
  firebase_auth_web: ^6.1.2
  firebase_core: ^4.4.0
  firebase_core_platform_interface: ^6.0.2
  firebase_core_web: ^3.4.0
  firebase_performance: ^0.11.1+4
  firebase_performance_platform_interface: ^0.1.6+4
  firebase_performance_web: ^0.1.8+2
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_secure_storage: ^10.0.0
  flutter_secure_storage_linux: ^3.0.0
  flutter_secure_storage_macos: 4.0.0
  flutter_secure_storage_platform_interface: 2.0.1
  flutter_secure_storage_web: ^2.1.0
  flutter_secure_storage_windows: ^4.1.0
  font_awesome_flutter: ^10.12.0
  from_css_color: 2.0.0
  google_fonts: ^7.0.2
  google_sign_in: ^7.2.0
  google_sign_in_android: ^7.2.7
  google_sign_in_ios: ^6.2.5
  google_sign_in_platform_interface: ^3.1.0
  google_sign_in_web: ^1.1.0
  http: 1.4.0
  intl: 0.20.2
  json_path: ^0.9.0
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.22
  path_provider_foundation: ^2.6.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  percent_indicator: ^4.2.5
  plugin_platform_interface: 2.1.8
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4
  shared_preferences_android: ^2.4.18
  shared_preferences_foundation: ^2.5.6
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.3
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: 7.0.1
  sign_in_with_apple_platform_interface: 2.0.0
  sign_in_with_apple_web: 3.0.0
  smooth_page_indicator: ^2.0.1
  sqflite: ^2.4.2
  sqflite_common: ^2.5.6
  stream_transform: ^2.1.1
  synchronized: 3.4.0
  timeago: 3.7.1
  url_launcher: ^6.3.2
  url_launcher_android: ^6.3.28
  url_launcher_ios: ^6.3.6
  url_launcher_linux: ^3.2.2
  url_launcher_macos: ^3.2.5
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.2
  url_launcher_windows: ^3.1.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  http: 1.4.0
  uuid: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/movia_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/movia_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/movia_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/movia_icon.png"

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/icons/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: Movie
      fonts:
        - asset: assets/fonts/movie.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
